[package]
name = "regex-classifier"
version = "0.1.0"
edition = "2021"
description = "A regex classifier for identifying data types"

[dependencies]
regex = "1.10.2"
lazy_static = "1.4.0"
clap = { version = "4.4.6", features = ["derive"] }